### ISSUE TITLE
Jupyter: Matlab Kernel Dies 

### ISSUE THREAD

**Issue by dbl001** [Calysto/matlab_kernel#22]
OS X 10.10.5
$ jupyter --version
4.0.4
Matlab R1025A

```
env | grep MATLAB_EXECUTABLE
MATLAB_EXECUTABLE=/Applications/MATLAB_R2015a.app/bin/matlab
David-Laxers-MacBook-Pro:OpenRefine davidlaxer$ jupyter notebook
[I 16:00:52.398 NotebookApp] Serving notebooks from local directory: /Users/davidlaxer/OpenRefine
[I 16:00:52.398 NotebookApp] 0 active kernels 
[I 16:00:52.398 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 16:00:52.398 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 16:01:05.861 NotebookApp] Creating new notebook in 
[I 16:01:06.573 NotebookApp] Kernel started: a3604dcd-9bfd-4f8c-ad6b-306b39ab906d
Traceback (most recent call last):
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/users/davidlaxer/anaconda/lib/python2.7/site-packages/matlab_kernel.py", line 4, in <module>
    from metakernel import MetaKernel
ImportError: No module named metakernel
[I 16:01:09.569 NotebookApp] KernelRestarter: restarting kernel (1/5)
Traceback (most recent call last):
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/users/davidlaxer/anaconda/lib/python2.7/site-packages/matlab_kernel.py", line 4, in <module>
    from metakernel import MetaKernel
ImportError: No module named metakernel
[I 16:01:12.577 NotebookApp] KernelRestarter: restarting kernel (2/5)
Traceback (most recent call last):
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/users/davidlaxer/anaconda/lib/python2.7/site-packages/matlab_kernel.py", line 4, in <module>
    from metakernel import MetaKernel
ImportError: No module named metakernel
[I 16:01:15.595 NotebookApp] KernelRestarter: restarting kernel (3/5)
Traceback (most recent call last):
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/users/davidlaxer/anaconda/lib/python2.7/site-packages/matlab_kernel.py", line 4, in <module>
    from metakernel import MetaKernel
ImportError: No module named metakernel
[W 16:01:16.684 NotebookApp] Timeout waiting for kernel_info reply from a3604dcd-9bfd-4f8c-ad6b-306b39ab906d
[I 16:01:18.606 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel a3604dcd-9bfd-4f8c-ad6b-306b39ab906d restarted
Traceback (most recent call last):
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/users/davidlaxer/anaconda/lib/python2.7/site-packages/matlab_kernel.py", line 4, in <module>
    from metakernel import MetaKernel
ImportError: No module named metakernel
[W 16:01:21.627 NotebookApp] KernelRestarter: restart failed
[W 16:01:21.628 NotebookApp] Kernel a3604dcd-9bfd-4f8c-ad6b-306b39ab906d died, removing from map.
ERROR:root:kernel a3604dcd-9bfd-4f8c-ad6b-306b39ab906d restarted failed!
[W 16:01:21.652 NotebookApp] Kernel deleted before session
[W 16:01:21.653 NotebookApp] 410 DELETE /api/sessions/312c44f9-d889-410e-a378-f9f6d5d526f3 (::1) 1.75ms referer=http://localhost:8888/notebooks/Untitled7.ipynb?kernel_name=matlab_kernel

```

![screen shot 2015-09-21 at 4 04 34 pm](https://cloud.githubusercontent.com/assets/3105499/10007479/8508ccca-607a-11e5-9597-db76edc92afd.png)
![screen shot 2015-09-21 at 4 04 24 pm](https://cloud.githubusercontent.com/assets/3105499/10007480/850b1f2a-607a-11e5-8402-065ee307b471.png)

**Comment by blink1073** [comment]
Did you install using `python setup.py install`?  Doing so doesn't install the dependencies automatically.  You can pick up metakernel by running `pip install metakernel`.

**Comment by dbl001** [comment]
```

$ pip install metakernel
Collecting metakernel
  Downloading metakernel-0.11.0-py2.py3-none-any.whl (115kB)
    100% |████████████████████████████████| 118kB 733kB/s 
Requirement already satisfied (use --upgrade to upgrade): IPython>=3.0 in /Users/davidlaxer/anaconda/lib/python2.7/site-packages (from metakernel)
Installing collected packages: metakernel
Successfully installed metakernel-0.11.0

Same thing:

[I 17:19:17.129 NotebookApp] Creating new notebook in 
[I 17:19:17.974 NotebookApp] Kernel started: 3f12592a-4ccf-4b32-8ab9-2f80f6f92d7e
Traceback (most recent call last):
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/users/davidlaxer/anaconda/lib/python2.7/site-packages/matlab_kernel.py", line 5, in <module>
    from pymatbridge import Matlab
ImportError: No module named pymatbridge
[I 17:19:20.984 NotebookApp] KernelRestarter: restarting kernel (1/5)
Traceback (most recent call last):
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/users/davidlaxer/anaconda/lib/python2.7/site-packages/matlab_kernel.py", line 5, in <module>
    from pymatbridge import Matlab
ImportError: No module named pymatbridge
[I 17:19:24.039 NotebookApp] KernelRestarter: restarting kernel (2/5)
Traceback (most recent call last):
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/users/davidlaxer/anaconda/lib/python2.7/site-packages/matlab_kernel.py", line 5, in <module>
    from pymatbridge import Matlab
ImportError: No module named pymatbridge
[I 17:19:27.049 NotebookApp] KernelRestarter: restarting kernel (3/5)
Traceback (most recent call last):
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/users/davidlaxer/anaconda/lib/python2.7/site-packages/matlab_kernel.py", line 5, in <module>
    from pymatbridge import Matlab
ImportError: No module named pymatbridge
[W 17:19:28.218 NotebookApp] Timeout waiting for kernel_info reply from 3f12592a-4ccf-4b32-8ab9-2f80f6f92d7e
[I 17:19:30.061 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 3f12592a-4ccf-4b32-8ab9-2f80f6f92d7e restarted
Traceback (most recent call last):
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/users/davidlaxer/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/users/davidlaxer/anaconda/lib/python2.7/site-packages/matlab_kernel.py", line 5, in <module>
    from pymatbridge import Matlab
ImportError: No module named pymatbridge
[W 17:19:33.148 NotebookApp] KernelRestarter: restart failed
[W 17:19:33.148 NotebookApp] Kernel 3f12592a-4ccf-4b32-8ab9-2f80f6f92d7e died, removing from map.
ERROR:root:kernel 3f12592a-4ccf-4b32-8ab9-2f80f6f92d7e restarted failed!
[W 17:19:33.164 NotebookApp] Kernel deleted before session
[W 17:19:33.165 NotebookApp] 410 DELETE /api/sessions/2040385f-706c-4a8e-b34e-07d4aa289046 (::1) 1.96ms referer=http://localhost:8888/notebooks/Untitled9.ipynb?kernel_name=matlab_kernel

```

**Comment by dbl001** [comment]
```

David-Laxers-MacBook-Pro:matlab_kernel davidlaxer$ python setup.py install
/users/davidlaxer/anaconda/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
running install_lib
running install_egg_info
Removing /users/davidlaxer/anaconda/lib/python2.7/site-packages/matlab_kernel-0.6.6-py2.7.egg-info
Writing /users/davidlaxer/anaconda/lib/python2.7/site-packages/matlab_kernel-0.6.6-py2.7.egg-info
/users/davidlaxer/anaconda/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
Installing kernel spec
David-Laxers-MacBook-Pro:matlab_kernel davidlaxer$ 

```

**Comment by blink1073** [comment]
You need `pip install pymatbridge`

**Comment by dbl001** [comment]
YES!

**Comment by blink1073** [comment]
Fixed?  In general I use `pip install .`, which grabs the dependencies for you.

**Comment by dbl001** [comment]
Yes, fixed!

>  `pip install .`
Got it!

Thank You!

**Comment by blink1073** [comment]
Cheers

**Comment by letskeepongoing** [comment]
> Cheers

i got the issue still and i cant do pip install .
Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
